### ISSUE TITLE
[ERROR] STOPPING EXTENT REPORT GENERATION - For input string: ""

### ISSUE THREAD

**Issue by sanketchandak** [grasshopper7/extentreports-cucumberjson-plugin#15]
Getting [ERROR] STOPPING EXTENT REPORT GENERATION - For input string: "" when test script fail.
Its saving screenshot but not generating pdf, json and spark report.
Whereas, when there are no failures it's creating all 3 reports.

----------------------------------------------------------------------------------------------------------

[INFO] --- extentreports-cucumberjson-plugin:2.5.0:extentreport (report) @ cucubrowse ---
[INFO] STARTED EXTENT REPORT GENERATION PLUGIN
[WARNING] Exception class not found with name - org.openqa.selenium.NoSuchElementException. Creating a generic exception instance.
[ERROR] STOPPING EXTENT REPORT GENERATION - For input string: ""

java.lang.NumberFormatException: For input string: ""
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:68)
	at java.base/java.lang.Integer.parseInt(Integer.java:668)
	at java.base/java.lang.Integer.parseInt(Integer.java:776)
	at tech.grasshopper.processor.ErrorMessageProcessor.createStackTrace(ErrorMessageProcessor.java:125)
	at tech.grasshopper.processor.ErrorMessageProcessor.createThrowableObject(ErrorMessageProcessor.java:48)
	at tech.grasshopper.test.heirarchy.ExtentTestHeirarchy.updateTestLogStatus(ExtentTestHeirarchy.java:203)
	at tech.grasshopper.test.heirarchy.ExtentTestHeirarchy.createStepExtentNode(ExtentTestHeirarchy.java:191)
	at tech.grasshopper.test.heirarchy.DefaultExtentTestHeirarchy.lambda$null$0(DefaultExtentTestHeirarchy.java:52)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at tech.grasshopper.test.heirarchy.DefaultExtentTestHeirarchy.lambda$null$1(DefaultExtentTestHeirarchy.java:48)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at tech.grasshopper.test.heirarchy.DefaultExtentTestHeirarchy.lambda$createTestHeirarchy$2(DefaultExtentTestHeirarchy.java:43)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at tech.grasshopper.test.heirarchy.DefaultExtentTestHeirarchy.createTestHeirarchy(DefaultExtentTestHeirarchy.java:39)
	at tech.grasshopper.test.ExtentTestManager.initialize(ExtentTestManager.java:33)
	at tech.grasshopper.ExtentReportsCucumberPlugin.execute(ExtentReportsCucumberPlugin.java:71)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)

**Comment by grasshopper7** [comment]
Can u add the stacktrace which is giving the error?

**Comment by grasshopper7** [comment]
try with version 2.6.0 and check

**Comment by sanketchandak** [comment]
Hi, I tried vs 2.6.0 and its working as expected.

Whe are you planning to release it officially because right now we are getting that version in red color but rest stuff working as expected.

**Comment by grasshopper7** [comment]
It is available in maven central. - https://search.maven.org/artifact/tech.grasshopper/extentreports-cucumberjson-plugin/2.6.0/maven-plugin
