### ISSUE TITLE
NPE when screenshot attached without name argument

### ISSUE THREAD

**Issue by grasshopper7** [grasshopper7/extentreports-cucumberjson-plugin#17]
[INFO] STARTED EXTENT REPORT GENERATION PLUGIN
java.lang.NullPointerException
at tech.grasshopper.json.deserializer.EmbeddedDeserializer.deserialize(EmbeddedDeserializer.java:27)
at tech.grasshopper.json.deserializer.EmbeddedDeserializer.deserialize(EmbeddedDeserializer.java:13)

**Comment by grasshopper7** [comment]
Fixed in 2.6.1
